
export const PROFIL_ETUDES = "PROFIL_ETUDES";

export const PROFIL_CQ = "PROFIL_CQ";

export const EXTRAIRE_NOM_LOT = "EXTRAIRE_NOM_LOT";
export const FILL_EMPTY_DYN = "FILL_EMPTY_DYN";
export const CONCATENER_CHAMPS = "CONCATENER_CHAMPS";
export const SI_AUTRE_CHAMP_RENSEIGNE = "SI_AUTRE_CHAMP_RENSEIGNE";
export const AJOUT_SEPARATEUR = "AJOUT_SEPARATEUR";
export const EXTRAIRE_NOM_IMAGE = "EXTRAIRE_NOM_IMAGE";
